### ISSUE TITLE
add-people-UI

### ISSUE THREAD

**Issue by nolan25** [LoloRigolo/bashgame#11]
environementale variable :  people

comande people -list:
-Show number of peoples
-Id of people

**Comment by LoloRigolo** [comment]
do it with poeple -list which return a Table (rich.table)
you need to modify :
- commands/utilities/function.py
- create your command in commands/people.py
- create the object in environmental_variables

Don't forget to make a test in :  test/test_people.py (library : pytest, command to launch tests : python -m pytest)
